name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "*/2 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
    - name: Badges - Readme
      uses: ASuelvesE/badge-readme@main
      with:       
        CREDLY_USER: asuelvese # optional, but default will use the same from github
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BADGE_SIZE: 100
